name: Label PRs
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: labler
         uses: "srvaroa/labeler@v0.2"
         env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
