name: Label PRs
on:
  pull_request:
    types:
      - opened
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: labler
         uses: "srvaroa/labeler@v0.2"
         env:
          GITHUB_TOKEN: "${{ secrets.ACTIONS_SECRET }}"
